services:
  postgres:
    image: "postgres:10-alpine"
    container_name: "postgres"
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - custom
      
  api:
    image: "node:12-alpine"
    container_name: "books-catalog-api"
    networks:
      - custom
    volumes:
      - "./src:/source/src"
      - "./package.json:/source/package.json"
      - "./yarn.lock:/source/yarn.lock"
      - "./.env:/source/.env"
      - "./babel.config.js:/source/babel.config.js"
      - "./knexfile.ts:/source/knexfile.ts"
      - "./tsconfig.json:/source/tsconfig.json"
    working_dir: /source
    depends_on:
      - postgres
    ports:
      - "${APP_PORT:-8000}:${APP_PORT:-8000}"
    command: sh -c "yarn && yarn start:dev"

volumes:
  pgdata:

networks:
  custom:
    driver: bridge